vim.lsp.config('*', {
	capabilities = require('blink.cmp').get_lsp_capabilities(),
})

vim.diagnostic.config({
	virtual_lines = true,
	underline = true,
	update_in_insert = true,
	severity_sort = true,
})

-- this function uses the normal goToDefinition from lsp if not in a golang file generated by templ
-- otherwise it will try to find the original file and go to the definition there
local go_to_definition = function()
	if vim.bo.filetype == "go" then
		vim.lsp.buf.definition({
			on_list = function(options)
				if options == nil or options.items == nil or #options.items == 0 then
					return
				end

				local targetFile = options.items[1].filename
				if not targetFile then
					vim.notify("No templ target file found, using default go to definition", vim.log.levels.WARN)
					vim.lsp.buf.definition()
					return
				end

				local prefix = string.match(targetFile, "(.-)_templ%.go$")

				vim.api.nvim_command('vsplit')
				if prefix then
					local function_name = vim.fn.expand('<cword>')
					options.items[1].filename = prefix .. ".templ"

					vim.fn.setqflist({}, ' ', options)
					vim.api.nvim_command('cfirst')

					vim.api.nvim_command('silent! /templ ' .. function_name)
				else
					vim.lsp.buf.definition()
				end
			end
		})
	else
		vim.lsp.buf.definition()
	end
end

vim.api.nvim_create_autocmd("LspAttach", {
	group = vim.api.nvim_create_augroup("lsp-attach", { clear = true }),
	callback = function(event)
		local map = function(keys, func, desc)
			vim.keymap.set("n", keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
		end

		-- map("fd", vim.diagnostic.open_float, "Open diagnostics float")
		map("K", vim.lsp.buf.hover, "Hover documentation")
		map("gs", vim.lsp.buf.signature_help, "Signature help")
		map("gD", vim.lsp.buf.declaration, "Go to declaration")
		map("gi", vim.lsp.buf.implementation, "Go to implementation")
		map("<leader>aa", vim.lsp.buf.code_action, "Code action")
		map("<leader>rn", vim.lsp.buf.rename, "Rename all references")
		map("<leader>fo", vim.lsp.buf.format, "Format buffer")
		map("gd", go_to_definition, "Go to lsp definition")
	end,
})
